/**
 * === JungleBook Default Next.js Config (ESM Safe) ===
 * Auto-generated by the JungleBook App Factory
 */

import path from "path";

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,

  webpack: (config) => {
    config.resolve.alias["@"] = path.resolve(__dirname, "src");
    return config;
  },
};

export default nextConfig;
